version: '3.3'
services:
  internal_db:
    image: mysql:8.0
    restart: unless-stopped
    container_name: internal-db
    environment: 
      MYSQL_ROOT_PASSWORD: ${SQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - kms_internal:/var/lib/mysql
    networks:
      - sql-net

volumes:
  kms_internal:

networks:
  sql-net:
    driver: bridge
