services:
  mcjv:
    container_name: minecraft-java
    image: itzg/minecraft-server
    stdin_open: true
    tty: true
    environment:
      EULA: "true"
      TYPE: "PAPER"
      PLUGINS: |
        https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
        https://dev.bukkit.org/projects/multiverse-core/files/latest
      GAMEMODE: creative
      DIFFICULTY: normal
      SERVER_NAME: "KMS MC JAVA"
      MAX_PLAYERS: ${MAX_PLAYES:-100}
      PLAYER_IDLE_TIMEOUT: ${IDLE_TIMEOUT:-60}
    ports:
      - "25565:25565"
      - "19132:19132/udp"
    volumes:
      - mc_java_data:/data
    
volumes:
  mc_java_data:
