version: "3.7"
services:
  app:
    image: lscr.io/linuxserver/plex:1.40.1.8227-c0dd5a73e-ls210
    container_name: plex
    #Enable the below options for Nvidia GPU discovery
    runtime: nvidia
    environment:
      - TZ=${TIMEZONE}
      - UMASK=022
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      #Enable the below options for Nvidia GPU discovery
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "32400:32400"
      - "32469:32469"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    volumes:
      - ${DATADIR}/plex-config:/config
      - ${DATADIR}/plex:/media
      - ${TRANSCODE_DIR}:/transcode
    restart: unless-stopped
    networks:
      - mdnet
  
  sabnzb:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzb
    ports:
      - "8080:8080"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - UMASK=002
    volumes:
      - ${DATADIR}/sabnzb/config:/config
      - ${DATADIR}/downloads:/downloads
      - ${DATADIR}/plex:/plex    
    restart: unless-stopped
    networks:
      - mdnet
    
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    ports:
      - "7878:7878"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - UMASK=002
    volumes:
      - ${DATADIR}/radarr-config:/config
      - ${DATADIR}/downloads:/downloads
      - ${DATADIR}/plex/movies:/movies
    restart: unless-stopped
    networks:
      - mdnet
    
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${DATADIR}/sonarr-config:/config
      - ${DATADIR}/downloads:/downloads
      - ${DATADIR}/plex/tv:/tv
    ports:
      - "8989:8989"
    restart: unless-stopped
    networks:
      - mdnet    
  
  ombi:
    image: lscr.io/linuxserver/ombi:latest
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${OMBI_CONFIG}:/config
    ports:
      - "3579:3579"
    restart: unless-stopped
    networks:
      - mdnet
      
networks:
  mdnet:
    driver: bridge
