services:
  mcbdr:
    container_name: minecraft_bedrock
    image: itzg/minecraft-bedrock-server
    environment:
      EULA: "TRUE"
      GAMEMODE: creative
      DIFFICULTY: normal
      SERVER_NAME: "KMS MC BDRCK"
      MAX_PLAYERS: ${MAX_PLAYERS:-100}
      PLAYER_IDLE_TIMEOUT: ${IDLE_TIMEOUT:-60}
    ports:
      - "19132:19132/udp"
    volumes:
      - mc-bdrck-data:/data
    stdin_open: true
    tty: true

volumes:
  mc-bdrck-data:
