version: '3.4'

services:
  mcbdr:
    container_name: minecraft
    image: itzg/minecraft-bedrock-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - EULA="TRUE"
      - GAMEMODE=creative
      - DIFFICULTY= normal
      - SERVER_NAME="KMS MC"
      - MAX_PLAYERS=100
      - LEVEL_TYPE=amplified
      - PLAYER_IDLE_TIMEOUT=60
    ports:
      - "19132:19132/udp"
    volumes:
      - /mc/data:/data
    stdin_open: true
    tty: true