version: "3.8"
services:      
  api:
    image: registry.kmserver.co/kms/kms/kmsapi:v1.0.10
    container_name: api
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - kms_net
  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORDHASH=${PASSWD}
    ports:
      - "8085:80"
      - "5341:5341"
    restart: unless-stopped
    volumes:
      - seq:/data
    networks:
      - kms_net
      
volumes:
  seq:
  
networks:
  kms_net:
    driver: bridge
