version: "3.8"
services:      
  api:
    image: ghcr.io/kmdeveloping/kms-api:v1.0.12-02.11.24
    container_name: api
    environment:
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - kms_net
  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORDHASH=${PASSWD}
    ports:
      - "8085:80"
      - "5341:5341"
    restart: unless-stopped
    volumes:
      - seq:/data
    networks:
      - kms_net
      
volumes:
  seq:
  
networks:
  kms_net:
    driver: bridge
