version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:latest
    container_name: ci
    restart: unless-stopped
    environment:
      - PGID=100
      - PUID=1000
      - TZ=America/Phoenix
    ports:
      - 8080:8080
      - 50000:50000
    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/var/jenkins_home
      
volumes:
  data:
