version: '3'
services:
  panel:
    image: scriptingonline/whmcs:8.3.0
    container_name: kms-whmcs
    restart: unless-stopped
    hostname: whmcs.xpro.dev
    ports:
      - "8085:80"
    volumes:
      - whmcs-downloads:/var/www/downloads
      - whmcs-templates:/var/www/attachments
      - whmcs-templates:/var/www/templates_c

volumes:
  whmcs-downloads:
  whmcs-templates:
  whmcs-attachments: