version: '3.5'

services:
  jf:
    image: jellyfin/jellyfin
    container_name: jf
    environment:
      - TZ=America/New_York
      - UID=1000
      - GID=1000
      - JELLYFIN_PublishedServerUrl=https://jf.kmsdev.io
    volumes:
      - ${HOST_DIRECTORY}/media:/media
      - config:/config
      - cache:/cache
    ports:
      - "8096:8096"
      - "8920:8920"
    networks:
      - jf_net
    restart: unless-stopped

  fs:
    image: filebrowser/filebrowser
    container_name: fs
    environment:
      - TZ=America/New_York
      - UID=1000
      - GID=1000
    ports:
      - "8080:80"
    volumes:
      - ${HOST_DIRECTORY}/media:/srv
      - ${HOST_DIRECTORY}/filebrowser.db:/database/filebrowser.db
    networks:
      - jf_net
    restart: unless-stopped

networks:
  jf_net:
    driver: bridge

volumes:
  config:
  cache: