version: "3"
services:
  grafana:
    image: grafana/grafana:latest
    container_name: "grafana"
    restart: unless-stopped
    environment:
      - TZ=America/Phoenix
    networks:
      - monitor
    ports:
      - 3010:3000
    volumes:
      - g_data:/var/lib/grafana
    depends_on: 
      db:
        condition: service_started
      varken:
        condition: service_started
  
  db:
    image: influxdb:1.8
    container_name: influx
    restart: unless-stopped
    environment:
      - TZ=America/Phoenix
    volumes:
      - db_data:/var/lib/influxdb2
    networks:
      - monitor
    ports:
      - 8086:8086
  
  tautulli:
    image: ghcr.io/tautulli/tautulli
    container_name: tautulli
    restart: unless-stopped
    volumes:
      - tau_data:/config
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Phoenix
    networks:
      - monitor
    ports:
      - 8181:8181

  telegraf:
    image: telegraf:alpine
    container_name: telegraf
    depends_on: 
      db:
        condition: service_started
    environment:
      - TZ=America/Phoenix
    user: telegraf:999
    volumes:
      - ${TELEGRAF_CONFIG_DIR}/telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - monitor
      
  varken:
    image: boerderij/varken:latest
    container_name: varken
    volumes:
      - vark_data:/config
    environment:
      - TZ=America/Phoenix
      - VRKN_GLOBAL_SONARR_SERVER_IDS=1
      - VRKN_GLOBAL_RADARR_SERVER_IDS=1
      - VRKN_GLOBAL_LIDARR_SERVER_IDS=false
      - VRKN_GLOBAL_TAUTULLI_SERVER_IDS=1
      - VRKN_GLOBAL_OMBI_SERVER_IDS=1
      - VRKN_GLOBAL_SICKCHILL_SERVER_IDS=false
      - VRKN_GLOBAL_UNIFI_SERVER_IDS=false
      - VRKN_GLOBAL_MAXMIND_LICENSE_KEY=${MM_LICENSE_KEY}
      - VRKN_INFLUXDB_URL=db
      - VRKN_INFLUXDB_PORT=8086
      - VRKN_INFLUXDB_SSL=false
      - VRKN_INFLUXDB_VERIFY_SSL=false
      - VRKN_INFLUXDB_USERNAME=root
      - VRKN_INFLUXDB_PASSWORD=root
      - VRKN_TAUTULLI_1_URL=tautulli:8181
      - VRKN_TAUTULLI_1_FALLBACK_IP=1.1.1.1
      - VRKN_TAUTULLI_1_APIKEY=${TAUT_API_KEY}
      - VRKN_TAUTULLI_1_SSL=false
      - VRKN_TAUTULLI_1_VERIFY_SSL=false
      - VRKN_TAUTULLI_1_GET_ACTIVITY=true
      - VRKN_TAUTULLI_1_GET_ACTIVITY_RUN_SECONDS=30
      - VRKN_TAUTULLI_1_GET_STATS=true
      - VRKN_TAUTULLI_1_GET_STATS_RUN_SECONDS=3600
      - VRKN_SONARR_1_URL=10.0.10.20:8989
      - VRKN_SONARR_1_APIKEY=${SONARR_API_KEY}
      - VRKN_SONARR_1_SSL=false
      - VRKN_SONARR_1_VERIFY_SSL=false
      - VRKN_SONARR_1_MISSING_DAYS=7
      - VRKN_SONARR_1_MISSING_DAYS_RUN_SECONDS=300
      - VRKN_SONARR_1_FUTURE_DAYS=1
      - VRKN_SONARR_1_FUTURE_DAYS_RUN_SECONDS=300
      - VRKN_SONARR_1_QUEUE=true
      - VRKN_SONARR_1_QUEUE_RUN_SECONDS=300
      - VRKN_RADARR_1_URL=10.0.10.20:7878
      - VRKN_RADARR_1_APIKEY=${RADARR_API_KEY}
      - VRKN_RADARR_1_SSL=false
      - VRKN_RADARR_1_VERIFY_SSL=false
      - VRKN_RADARR_1_QUEUE=true
      - VRKN_RADARR_1_QUEUE_RUN_SECONDS=300
      - VRKN_RADARR_1_GET_MISSING=true
      - VRKN_RADARR_1_GET_MISSING_RUN_SECONDS=300
      - VRKN_OMBI_1_URL=ombi.kmserver.co
      - VRKN_OMBI_1_APIKEY=${OMBI_API_KEY}
      - VRKN_OMBI_1_SSL=true
      - VRKN_OMBI_1_VERIFY_SSL=true
      - VRKN_OMBI_1_GET_REQUEST_TYPE_COUNTS=true
      - VRKN_OMBI_1_REQUEST_TYPE_RUN_SECONDS=300
      - VRKN_OMBI_1_GET_REQUEST_TOTAL_COUNTS=true
      - VRKN_OMBI_1_REQUEST_TOTAL_RUN_SECONDS=300
      - VRKN_OMBI_1_GET_ISSUE_STATUS_COUNTS=true
      - VRKN_OMBI_1_ISSUE_STATUS_RUN_SECONDS=300
    depends_on: 
      db:
        condition: service_started
    networks:
      - monitor

volumes:
  g_data:
  tau_data:
  db_data:
  vark_data:

networks:
  monitor:
    driver: bridge
