version: "3.7"
services:
  cache:
    image: redis
    container_name: "redis_1"
    restart: unless-stopped
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=100
    ports:
      - "5005:6379"
      
    volumes:
      - redis-data:/data
      
volumes:
  redis-data:
